---
- name: Update apt cache
  yum: name=* state=present
  sudo: yes

- name: Install required software
  yum: name={{ item }} state=present
  sudo: yes
  with_items:
    - httpd
    - mysql-server
    - php-mysql
    - php
    - libselinux-python
#    - libapache2-mod-php5
#    - php5-mcrypt
#    - python-mysqldb

- name: Start http service
  service: name=httpd state=started
  sudo: yes
